export const recipes = [
  {
    slug: "honey-soy-air-fryer-salmon",
    name: "Honey soy air fryer salmon",
    items: [
      "2 salmon fillets (130–180 g each)",
      "1 tbsp soy sauce",
      "1 tbsp honey",
      "1 tsp lemon juice",
      "1 tsp olive oil",
      "1 garlic clove, grated",
      "A little bit of ginger",
    ],
    instructions: [
      "Mix everything into a paste.",
      "Pat the salmon dry and coat the top and sides with the glaze.",
      "Marinate for 10–20 minutes.",
      "Preheat the air fryer to 190°C for 3 minutes.",
      "Cook skin-side down: 7–9 minutes for medium, or 10–12 minutes for thoroughly cooked salmon.",
    ],
  },
  {
    slug: "cottage-cheese-casserole",
    name: "Cottage cheese casserole",
    items: [
      "600 g cottage cheese",
      "3 eggs",
      "5 tbsp wheat flour",
      "3 tbsp sugar",
      "100 g frozen blueberries",
      "100 g frozen cherries",
      "Air fry at 160°C for 23 minutes",
    ],
  },
  {
    slug: "savory-cottage-cheese-bake",
    name: "Savory cottage cheese bake",
    items: [
      "Cottage cheese",
      "Eggs",
      "Grated mozzarella",
      "Tomato",
      "Spinach",
      "Garlic",
      "Air fry at 170°C for 25 minutes",
    ],
  },
  {
    slug: "pancakes",
    name: "Pancakes",
    items: [
      "1.3 L milk",
      "500 g flour",
      "3 eggs",
      "2 tbsp sugar",
      "½ tbsp salt",
      "Sunflower oil — enough to fill a glass to a depth of about 1.5 cm",
    ],
  },
];
